### PR TITLE
Catch URLs for nicknames in nickname and nickall commands

### PR DESCRIPTION
**Pull request by ks129**

### CODE REVIEW

**Review by kyle-he — CHANGES_REQUESTED** [review]
Can you move the regex to helpers/constants.py

**Comment by oliver-ni** [comment]
> Can you move the regex to helpers/constants.py

I actually don't mind it here, but I *would* prefer `search` vs `findall`.

**Comment by ks129** [comment]
@oliver-ni I still decided to move this to constants, because then this can be used in other cogs as well in future. Also changed `findall` to `search`.

**Review by oliver-ni — APPROVED** [review]
Thank you!

**Pull request merged**
