### PR TITLE
Add basic anti-cheat

### PR DESCRIPTION
**Pull request by kyle-he**
used Pillow to adjust sharpness to change image hash but not visual appearance of pokemon

### CODE REVIEW

**Comment by kyle-he** [comment]
does not work as of now, working on it

**Comment by Kr4ken-9** [comment]
This could be done in bulk on the image collection beforehand instead of at runtime, in case performance is a concern.

**Comment by oliver-ni** [comment]
@kyle-he I don't think it's feasible to alter the image slightly to prevent autocatchers. phash works really well even if the images aren't exactly the same.

Best bet is to log catching times and take action on insanely fast catchers.

**Comment by ExtraConcentratedJuice** [comment]
I've tried preventing autocatching on one of my own bots a while back, and messing with the image will not work unless you screw it beyond comprehension. However, this method works well against "dumb" autocatchers which don't use an image hashing algorithm, so it doesn't hurt to implement it. Having the image be served from a webserver which alters a pixel or two to change hashes will screw anybody who has an already functioning "dumb" autocatcher. For "smart" autocatchers, it would be wise to add trade logging and code to flag large trades, since most autocatch users will often run the program on an alternate account. In addition to logging catch times, it would also be wise to log the duration between catches to stop autocatchers that run 24 hours a day. I have also thought about adding a CAPTCHA in the past, but that would ruin the user experience.

While some features can be implemented to stop autocatchers, in the end they can be almost indistinguishable from a human if implemented correctly. Your best bet is to log trades, log catch times and generate statistics for catches, and have a moderator team review logs, interrogate, then ban anybody who is suspicious.

**Pull request closed without merging**
