### PR TITLE
Enhancement: Accept caps. in Custom Prefixes

### PR DESCRIPTION
**Pull request by michaelsong4399**
Per community suggestion by Wenoh#6969 in post https://discord.com/channels/716390832034414685/719100172491161640/793692136784527370 , enables bot acceptance of capitalized (first letter) custom server prefixes to enhance typing experience of mobile players.

**Affected Users:** Servers with custom prefixes, since default prefixes p! and P! are both currently accepted.
**Advantage:** On mobile, first letters are automatically capitalized, giving mobile players disadvantage in catching. This PR solves this issue. 
**Drawback:** limits available (free) bot prefixes on server, **might cause bot interference** in some servers with lower and uppercase commands for different bots.

Due to the **potential drawbacks** above, please determine if this enhancement is a **needed** feature and if an update announcement in OS is needed (for players to adjust accordingly) before merge.

Thank you.

### CODE REVIEW

**Comment by oliver-ni** [comment]
I've thought about this but I never figured out how it should be done. This is largely the reason it's not here in the first place.

With your PR, it'll capitalize the first character and add that to the list of accepted prefixes. This works fine for things like `p.`. But what about things with multiple letters or something that doesn't start with a letter? Like `/p ` or `poketwo!`... 

Also, should we automatically lowercase if it's given capitalized? What if people want case-sensitive prefixes for different bots? I'm honestly not sure how often people would actually want that.

Another logical option would just be to casefold the prefix and match it onto the casefolded message content, so any combination of caps would match. Casefolding would also require modifications to dpy itself (or, more likely, overriding some function in the `Bot` class)

We also might just go with allowing *multiple* prefixes to be added instead of just one, then people can configure it however they want.

What do you (and other community members) think?

**Comment by michaelsong4399** [comment]
Regarding the first point, .capitalize() seems to "ignore" capitalizing starting chars for all printable chars and would not throw an error, just like how mobile users wont be able to auto-capitalize starting characters because there isn't a capitalized version.

When setting custom prefixes, we could limit them to only be able to use chars from string.printable (since there would be no apparent reason for people to use special chars)

Screen Shot 2020-12-30 at 2 12 48 AM

I am currently rethinking about the second issue. (auto .lower() and other formatting during custom prefix creation)

**Comment by kyle-he** [comment]
I would say the most straightforward approach to fixing this would be to add multi-prefix support. (Similar to [RoboDanny](https://github.com/Rapptz/RoboDanny))

**Comment by michaelsong4399** [comment]
Ah. I agree with Kyle, I think multi-prefix (and limit it to 3-10) definitely works and it is a great idea. Do we still want to include the .capitalize() function or just let the users set it up themselves?
Because when the mobile users type it, they do @poketwo prefix (prefix) (automatically without the caps), but when they actually type it out as the first word the first letter is always going to be auto-capped. I was thinking that setting it to accept both cap and lower versions could make life easier for the users.

I guess here are the three current ideas:
1. Multi-prefix
2. Accepting both cap and lower versions of first letter
3. Both 1 and 2

I am fine with implementing any of three. What do you guys think?

To implement multi-prefix, do we have to change prefix data structure stored in MongoDB from a string to an nparray? Or is MongoDB already expandable (so we that can pass in as an nparray and it can store as a list of strings)? How would that exactly work? Thanks.
https://github.com/oliver-ni/poketwo/blob/bd17392838cfba76566545f91cdac3495b06b5fb/cogs/config.py#L77
https://github.com/oliver-ni/poketwo/blob/bd17392838cfba76566545f91cdac3495b06b5fb/cogs/config.py#L96-L97

RoboDanny's code can definitely be considered/replicated for the user-poketwo and poketwo-discord connections.
Poketwo-Discord: https://github.com/Rapptz/RoboDanny/blob/715a5cf8545b94d61823f62db484be4fac1c95b1/bot.py#L44-L52
User-Poketwo: https://github.com/Rapptz/RoboDanny/blob/715a5cf8545b94d61823f62db484be4fac1c95b1/cogs/meta.py#L256-L342

**Pull request closed without merging**
