### PR TITLE
Add bare-bones anticheat

### PR DESCRIPTION
**Pull request by kyle-he**

### CODE REVIEW

**Comment by silasary** [comment]
This will throw off anyone who uses md5 hashing, but doesn't affect phashes at all.

**Comment by kyle-he** [comment]
Yep, I mentioned that in my comment on issue #1 . I experimented with adding a background but people were generally against it. This is to deter the md5 autocatchers.

**Comment by oliver-ni** [comment]
I am in support of the grass field idea, if we can get it to look nice. Would also make the bot *slightly* less boring

**Comment by silasary** [comment]
If you want an adversary to test against, https://github.com/silasary/professor_oak/ uses most of the techniques needed to bypass anti-cheat mechanisms that Pokecord used.  

Even some really weird ones, like [Homograph attacks](https://en.wikipedia.org/wiki/IDN_homograph_attack) in the text it sent. (They loved randomly replacing a with [а (U+0430)](https://en.wikipedia.org/wiki/A_(Cyrillic)) for example)

**Comment by kyle-he** [comment]
Thanks for the insight, I'll definitely take a look at that. Also, since you have some experience with Pokecord anti-cheat mechanisms, is it possible if you could DM me (keelay#0001, these comments are publically available on the server) some of the anti-cheats Pokecord used so we can implement some of them into this bot.

**Comment by oliver-ni** [comment]
@kyle-he lol, the code is there for everyone to see anyway

**Comment by kyle-he** [comment]
Success! The backgrounds were chosen on the fly, so all there is left to do it to change the backgrounds to something more reasonable. I am planning on manually tagging each Pokemon with a suitable background, (in the air, on grass, in cave...)

image
image

**Comment by silasary** [comment]
Nice!  (But damn, now I need to work out how to beat it :P)

**Comment by oliver-ni** [comment]
Definitely not foolproof, but will probably deter most. great work!

**Comment by oliver-ni** [comment]
Not foolproof, but will probably deter most. great work!

**Comment by mahrcel** [comment]
Only took like 15 minutes of coding to bypass it. Different backgrounds will definitely make it more tedious though. Nice job so far!

**Comment by kyle-he** [comment]
@mahrcel would you care to share how you bypassed it?

**Comment by mahrcel** [comment]
@kyle-he Created a single dataset of images with your code and hashed them with [image-match](https://github.com/EdjoLabs/image-match). Wish there was more to it 🤷🏻‍♂️

**Comment by kyle-he** [comment]
Oh, do you mean you generated every single possible spawn image the bot can make? I had to read that a couple times, but I think I get what you are coming from now. I have some ideas to fix that later on (add more environments with more room to change, dynamic weather now that we have server locations...) but that seems to be a valid concern.

**Comment by mahrcel** [comment]
I ran the Pokétwo image generation script only once for every Pokémon, then hashed it. Leaving me with only one hash per Pokémon. The approximation is still close enough to get a 100% match. At least with the current background used.

Having the size and position of the Pokémon be dynamic would probably be your best bet against bots that use hashing.

**Pull request merged**
